name: Deploy

on:
  push:
    branches:
      - master  # Change to main if your default branch is main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2  # Updated to v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install  # Use npm install directly

      - name: Set up environment variables
        run: |
          echo "VITE_EMAIL_TOKEN=${{ secrets.VITE_EMAIL_TOKEN }}" >> $GITHUB_ENV

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./dist

      - name: Debug Environment Variables
        run: printenv | grep VITE

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2  # This ensures the repo is checked out in the deploy step

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./dist

      - name: Debug Environment Variables in deploy
        run: printenv | grep VITE

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
