name: Deploy

on:
  push:
    branches:
      - master 

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

       - name: Debug Secrets
        run: echo "VITE_EMAIL_TOKEN=${{ secrets.VITE_EMAIL_TOKEN }}"  # Temporarily print secret value to check
        
      - name: Set up environment variables
        run: |
          echo "VITE_EMAIL_TOKEN=${{ secrets.VITE_EMAIL_TOKEN }}" >> $GITHUB_ENV

      - name: Build project
        run: npm run build

      - name: Debug Environment Variables on build
        run: printenv | grep VITE

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
